version: "3"

services:
  apache:
    build:
      args:
        versao_php: 7.2
      context: ./.apache
    container_name: sel-apache
    volumes:
      - ../.:/var/www/html
      - ./.apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.apache/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8042:80"
      - "443:443"
    networks:
      - network-sel
    depends_on:
      - db

  db:
    image: mariadb:10.1.41
    container_name: sel-mariadb

    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: r15987
      MYSQL_DATABASE: sel
      MYSQL_USER: sel
      MYSQL_PASSWORD: sel4631
    networks:
      - network-sel

networks:
  network-sel:
    driver: bridge
